name: ruben-reversi # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: git # just for humans, typically '1.2+git' or '1.3.2'
summary: Command-line version of the classic Reversi / Othello game # 79 char long summary
description: |
  Command-line version of the classic Reversi game (also referred to as Othello).
  
  Supports both the modern Othello rules and the historical Reversi rules.

  Run the game using the following command: `ruben-reversi`.

  For more information, see: https://github.com/Ruben9922/reversi/blob/master/README.md.
license: GPL-3.0+

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  ruben-reversi:
    command: bin/reversi

parts:
  ruben-reversi:
    plugin: go
    source: .
